---
- name: install essential packages (this may take a while)
  pacman: name="{{ item }}"
  with_items:
  - base-devel
  - btrfs-progs
  - bc
  - git
  - gstreamer-vaapi
  - gst-libav
  - i2c-tools
  - inetutils
  - intel-ucode
  - kmod
  - libelf
  - mesa
  - openssl-1.0
  - pulseaudio
  - thermald
  - tlp
  - xf86-video-intel
  - xorg-xrandr
  notify:
  - enable thermal services
  tags:
  - packages