---
- name: fix mkinitcpio config
  lineinfile:
    path: /etc/mkinitcpio.conf
    regexp: "^{{ item.key }}="
    line: "{{ item.key }}=\"{{ item.value }}\""
    create: yes
  with_items:
  - { key: 'HOOKS', value: 'base udev block autodetect modconf filesystems fsck' }
  - { key: 'MODULES', value: 'btusb pwm-lpss pwm-lpss-platform' }
  notify:
  - update boot
  tags:
  - boot

