---
- name: add modules to initramfs
  lineinfile:
    path: /etc/initramfs-tools/modules
    line: "{{ item }}"
    create: yes
  with_items:
  - btusb
  - pwm-lpss
  - pwm-lpss-platform
  notify:
  - update boot
  tags:
  - boot