---
- name: add modules to initramfs
  lineinfile:
    path: /etc/initramfs-tools/modules
    line: "{{ item }}"
    create: yes
  with_items:
  - btusb
  - pwm-lpss
  - pwm-lpss-platform
  notify:
  - update initrd
  - update grub
  tags:
  - boot

- name: fetch latest prebuilt kernel (this will take a while)
  git:
    repo: https://github.com/cawilliamson/linux-gpdpocket.git
    dest: /usr/src/linux-gpdpocket
    force: yes
  notify:
  - update initrd
  - update grub
  register: kernel_sources
  tags:
  - boot

- name: install kernel modules
  make:
    chdir: /usr/src/linux-gpdpocket
    target: modules_install
  notify:
  - update initrd
  - update grub
  when: kernel_sources.changed
  tags:
  - boot

- name: install new kernel
  copy:
    src: /usr/src/linux-gpdpocket/arch/x86/boot/bzImage
    dest: /boot/vmlinuz-4.12.0-gpdpocket
    owner: root
    group: root
    mode: 0644
  notify:
  - update initrd
  - update grub
  when: kernel_sources.changed
  tags:
  - boot

- name: add boot options to grub
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT='
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="i915.fastboot=1 i915.semaphores=1"'
  notify:
  - update initrd
  - update grub
  tags:
  - boot

- name: reduce grub timeout
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_TIMEOUT='
    line: 'GRUB_TIMEOUT=3'
  notify:
  - update initrd
  - update grub
  tags:
  - boot