---
- name: add modules to initramfs
  lineinfile:
    path: /etc/dracut.conf
    line: "add_drivers+=\"{{ item }}\""
    create: yes
  with_items:
  - btusb
  - pwm-lpss
  - pwm-lpss-platform
  notify:
  - update boot
  tags:
  - boot