---
- name: fetch latest prebuilt kernel (this may take a while)
  git:
    repo: https://github.com/cawilliamson/linux-gpdpocket.git
    dest: /usr/src/linux-gpdpocket
    version: "{{ BRANCH | default('master') }}"
    force: yes
  register: kernel_sources
  tags:
  - boot

- name: install kernel modules (this may take a while)
  make:
    chdir: /usr/src/linux-gpdpocket
    target: modules_install
  notify:
  - update boot
  when: kernel_sources.changed
  tags:
  - boot

- name: install new kernel
  copy:
    src: /usr/src/linux-gpdpocket/arch/x86/boot/bzImage
    dest: /boot/vmlinuz-4.12.0-gpdpocket
    owner: root
    group: root
    mode: 0644
  notify:
  - update boot
  when: kernel_sources.changed
  tags:
  - boot

- include: arch.yml
  when: ansible_distribution == 'Archlinux'

- include: debian.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- include: gentoo.yml
  when: ansible_distribution == 'Gentoo'

- name: set grub boot options
  lineinfile:
    path: /etc/default/grub
    regexp: "^{{ item.key }}="
    line: "{{ item.key }}={{ item.value }}"
  with_items:
  - { key: 'GRUB_CMDLINE_LINUX_DEFAULT', value: '"i915.fastboot=1 i915.semaphores=1"' }
  - { key: 'GRUB_DEFAULT', value: 'saved' }
  - { key: 'GRUB_TIMEOUT', value: '3' }
  notify:
  - update boot
  tags:
  - boot