---
- name: create xorg directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
  - /etc/X11/xorg.conf.d
  - /etc/X11/Xsession.d
  tags:
  - xorg

- name: copy xorg configs
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  register: xorg_configs
  with_items:
  - { src: 'files/01touchscreen', dest: '/etc/X11/Xsession.d/' }
  - { src: 'files/02gpdrotate', dest: '/etc/X11/Xsession.d/' }
  - { src: 'files/20-intel.conf', dest: '/etc/X11/xorg.conf.d/' }
  - { src: 'files/80-screen.conf', dest: '/etc/X11/xorg.conf.d/' }
  - { src: 'files/90-monitor.conf', dest: '/etc/X11/xorg.conf.d/' }
  tags:
  - xorg

- name: copy gpdrotate script
  copy:
    src: files/gpdrotate.sh
    dest: /usr/local/sbin/gpdrotate
    owner: root
    group: root
    mode: 0777
  tags:
  - xorg

- name: copy systemd service for gpdrotate
  copy:
    src: files/gpdrotate.service
    dest: /etc/systemd/system/gpdrotate.service
    owner: root
    group: root
    mode: 0644
  notify:
  - enable gpdrotate
  tags:
  - xorg

- name: create dconf directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
  - /etc/dconf/db/local.d
  - /etc/dconf/profile
  tags:
  - xorg

- name: set gnome interface scaling
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
  - { src: 'files/03scaling', dest: '/etc/dconf/db/local.d/' }
  - { src: 'files/dconf-profile-user', dest: '/etc/dconf/profile/user' }
  notify:
  - update dconf
  ignore_errors: yes
  tags:
  - xorg

- name: disable wayland on gdm
  lineinfile:
    path: /etc/gdm3/custom.conf
    regexp: '^#WaylandEnable=false'
    line: 'WaylandEnable=false'
    backrefs: yes
  ignore_errors: yes
  tags:
  - xorg