---
- name: create xorg directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
  - /etc/X11/xorg.conf.d
  - /etc/X11/Xsession.d
  tags:
  - xorg

- name: copy xorg configs
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  register: xorg_configs
  with_items:
  - { src: 'files/01touchscreen', dest: '/etc/X11/Xsession.d/' }
  - { src: 'files/02gpdrotate', dest: '/etc/X11/Xsession.d/' }
  - { src: 'files/03scaling', dest: '/etc/X11/Xsession.d/' }
  - { src: 'files/20-intel.conf', dest: '/etc/X11/xorg.conf.d/' }
  - { src: 'files/80-screen.conf', dest: '/etc/X11/xorg.conf.d/' }
  - { src: 'files/90-monitor.conf', dest: '/etc/X11/xorg.conf.d/' }
  tags:
  - xorg

- name: copy gpdrotate script
  copy:
    src: files/gpdrotate.sh
    dest: /usr/local/sbin/gpdrotate
    owner: root
    group: root
    mode: 0777
  tags:
  - xorg

- name: copy systemd service for gpdrotate
  copy:
    src: files/gpdrotate.service
    dest: /etc/systemd/system/gpdrotate.service
    owner: root
    group: root
    mode: 0644
  notify:
  - enable gpdrotate
  tags:
  - xorg

- name: set gdm scaling
    su - gdm -c "DISPLAY=:0 XAUTHORITY=$(ps aux |grep -e Xorg | head -n1 | awk '{ split($0, a, "-auth "); split(a[2], b, " "); print b[1] }') gsettings reset org.gnome.settings-daemon.plugins.xsettings overrides"
    su - gdm -c "DISPLAY=:0 XAUTHORITY=$(ps aux |grep -e Xorg | head -n1 | awk '{ split($0, a, "-auth "); split(a[2], b, " "); print b[1] }') gsettings set org.gnome.desktop.interface scaling-factor 1"
    su - gdm -c "DISPLAY=:0 XAUTHORITY=$(ps aux |grep -e Xorg | head -n1 | awk '{ split($0, a, "-auth "); split(a[2], b, " "); print b[1] }') gsettings set org.gnome.desktop.interface text-scaling-factor 1"
  changed_when: false
  ignore_errors: yes
  tags:
  - xorg

- name: disable wayland on gdm
  lineinfile:
    path: /etc/gdm3/custom.conf
    regexp: '^#WaylandEnable=false'
    line: 'WaylandEnable=false'
  ignore_errors: yes
  tags:
  - xorg