---
- name: create gpd-rotate directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
  - /etc/X11/Xsession.d
  - /etc/X11/xinit/xinitrc.d
  tags:
  - gnome
  - xorg

- name: copy gpd-rotate files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  with_items:
  - { src: 'files/rotate/01gpd-rotate', dest: '/etc/X11/Xsession.d/01gpd-rotate', mode: '0644' }
  - { src: 'files/rotate/01gpd-rotate', dest: '/etc/X11/xinit/xinitrc.d/01gpd-rotate', mode: '0777' }
  - { src: 'files/rotate/gpd-rotate.conf', dest: '/etc/gpd/rotate.conf', mode: '0644' }
  - { src: 'files/rotate/gpd-rotate.py', dest: '/usr/local/sbin/gpd-rotate', mode: '0777' }
  - { src: 'files/rotate/gpd-rotate.service', dest: '/etc/systemd/system/gpd-rotate.service', mode: '0644' }
  notify:
  - enable gpd-rotate
  tags:
  - rotate
  - xorg