---
- name: copy gpd-fan script
  copy:
    src: files/gpd-fan.py
    dest: /usr/local/sbin/gpd-fan
    owner: root
    group: root
    mode: 0777
  tags:
  - fan
  - power

- name: add suspend script for gpd-fan
  copy:
    src: files/gpd-fan.sh
    dest: /lib/systemd/system-sleep/gpd-fan
    owner: root
    group: root
    mode: 0777
  tags:
  - fan
  - power

- name: copy config file for gpd-fan
  copy:
    src: files/gpd-fan.conf
    dest: /etc/gpd/fan.conf
    owner: root
    group: root
    mode: 0644
  tags:
  - fan
  - power

- name: copy systemd service for gpdfand
  copy:
    src: files/gpd-fan.service
    dest: /etc/systemd/system/gpd-fan.service
    owner: root
    group: root
    mode: 0644
  notify:
  - enable gpd-fan
  tags:
  - fan
  - power