---
- name: set tlp disk devices
  lineinfile:
    path: /etc/default/tlp
    regexp: '^DISK_DEVICES='
    line: 'DISK_DEVICES="mmcblk0"'
  notify:
  - enable thermal services
  tags:
  - power
  - tlp