---
- name: set tlp options
  lineinfile:
    path: /etc/default/tlp
    regexp: "^{{ item.key }}="
    line: "{{ item.key }}=\"{{ item.value }}\""
  with_items:
  - { key: 'DISK_DEVICES', value: 'mmcblk0' }
  - { key: 'DISK_IOSCHED', value: 'sfq' }
  notify:
  - enable thermal services
  tags:
  - power
  - tlp