---
- name: copy wifi config file to device
  copy:
    src: files/brcmfmac4356-pcie.txt
    dest: /lib/firmware/brcm/brcmfmac4356-pcie.txt
    owner: root
    group: root
    mode: 0644
    
- name: prevent suspend from breaking wifi
  lineinfile:
    path: /etc/pm/config.d/config
    lineinfile: SUSPEND_MODULES="brcmfmac"