---
- name: copy wifi config file to device [arch]
  copy:
    src: files/brcmfmac4356-pcie.txt
    dest: /usr/lib/firmware/brcm/brcmfmac4356-pcie.txt
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution == 'Archlinux'
  tags:
  - wifi

- name: copy wifi config file to device [debian]
  copy:
    src: files/brcmfmac4356-pcie.txt
    dest: /lib/firmware/brcm/brcmfmac4356-pcie.txt
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  tags:
  - wifi

- name: prevent suspend from breaking wifi
  lineinfile:
    path: /etc/pm/config.d/config
    line: SUSPEND_MODULES="brcmfmac"
    create: yes
  tags:
  - wifi