---
- name: copy wifi firmware to device
  copy:
    src: files/brcmfmac4356-pcie.bin
    dest: /lib/firmware/brcm/brcmfmac4356-pcie.bin
    owner: root
    group: root
    mode: 0644
  tags:
  - wifi

- name: copy wifi config file to device
  copy:
    src: files/brcmfmac4356-pcie.txt
    dest: /lib/firmware/brcm/brcmfmac4356-pcie.txt
    owner: root
    group: root
    mode: 0644
  tags:
  - wifi

- name: prevent suspend from breaking wifi
  lineinfile:
    path: /etc/pm/config.d/config
    line: SUSPEND_MODULES="brcmfmac"
    create: yes
  tags:
  - wifi