---
- name: add bluetooth udev rule
  lineinfile:
    path: /etc/udev/rules.d/99-local-bluetooth.rules
    line: SUBSYSTEM=="usb", ATTRS{idVendor}=="0000", ATTRS{idProduct}=="0000", RUN+="/bin/sh -c 'modprobe btusb; echo 0000 0000 > /sys/bus/usb/drivers/btusb/new_id'"
    create: yes
  tags:
  - bluetooth
