---
- name: create touchscreen config
  copy:
    src: files/01touchscreen
    dest: /etc/X11/Xsession.d/01touchscreen
    owner: root
    group: root
    mode: 0777
      
- name: install necessary packages for video acceleration
  apt: name="{{ item }}"
  with_items:
  - gstreamer1.0-libav
  - gstreamer1.0-plugins-bad-faad
  - gstreamer1.0-vaapi
  - i965-va-driver
  - mesa-utils
  
- name: create xorg config for display rotation
  copy:
    src: 21-monitor.conf
    dest: /etc/X11/xorg.conf.d/21-monitor.conf
    owner: root
    group: root
    mode: 0644
