---
- name: create touchscreen config
  copy:
    src: files/01touchscreen
    dest: /etc/X11/Xsession.d/01touchscreen
    owner: root
    group: root
    mode: 0777
      
- name: install necessary packages for video acceleration
  apt: name="{{ item }}"
  with_items:
  - gstreamer1.0-libav
  - gstreamer1.0-plugins-bad-faad
  - gstreamer1.0-vaapi
  - i965-va-driver
  - mesa-utils
  
- name: copy monitors.xml config in to place
  shell: |
    # install for users
    for USER in $(ls /home); do
      mkdir -p /home/${USER}/.config/
      cp -f roles/display/files/monitors.xml /home/${USER}/.config/monitors.xml
      chown -R ${USER}:${USER} /home/${USER}/.config/
    done
    
    # install for gdm
    if [ -d /var/lib/gdm3/.config ]; then
      cp -f roles/display/files/monitors.xml /var/lib/gdm3/.config/monitors.xml
      chown gdm:gdm /var/lib/gdm3/.config/monitors.xml
    fi
    
    # install for lightdm
    if [ -d /var/lib/lightdm/.config ]; then
      cp -f roles/display/files/monitors.xml /var/lib/lightdm/.config/monitors.xml
      chown lightdm:lightdm /var/lib/lightdm/.config/monitors.xml
    fi