---
- name: install xrandr [arch]
  pacman: name=xorg-xrandr
  when: ansible_distribution == 'Archlinux'
  tags:
  - display

- name: install xrandr [debian]
  apt: name=x11-xserver-utils
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  tags:
  - display

- name: create xorg configs
  copy:
    src: "{{ item }}"
    dest: /etc/X11/Xsession.d/
    owner: root
    group: root
    mode: 0644
  register: xorg_configs
  with_items:
  - files/01touchscreen
  - files/02scale
  tags:
  - display

- name: copy gpdrotate script
  copy:
    src: files/gpdrotate.sh
    dest: /usr/local/sbin/gpdrotate
    owner: root
    group: root
    mode: 0777
  tags:
  - display

- name: copy systemd service for gpdrotate
  copy:
    src: files/gpdrotate.service
    dest: /etc/systemd/system/gpdrotate.service
    owner: root
    group: root
    mode: 0644
  notify:
  - reload systemd
  - enable service
  tags:
  - display
  
- name: copy xsession.d script for gpdrotate
  copy:
    src: files/98gpdrotate
    dest: /etc/X11/Xsession.d/98gpdrotate
    owner: root
    group: root
    mode: 0644
  tags:
  - display