---
- name: create xorg configs
  copy:
    src: "{{ item }}"
    dest: /etc/X11/Xsession.d/
    owner: root
    group: root
    mode: 0777
  register: xorg_configs
  with_items:
  - files/01touchscreen
  - files/02scale
  tags:
  - display

- name: copy monitors.xml config in to place
  shell: |
    # install for users
    for USER in $(ls /home); do
      mkdir -p /home/${USER}/.config/
      cp -f roles/display/files/monitors.xml /home/${USER}/.config/monitors.xml
      chown -R ${USER}:${USER} /home/${USER}/.config/
    done
    
    # install for gdm
    if [ -d "/var/lib/gdm3/.config" ]; then
      cp -f roles/display/files/monitors.xml /var/lib/gdm3/.config/monitors.xml
      chown gdm:gdm /var/lib/gdm3/.config/monitors.xml
    fi
    
    # install for lightdm
    if [ -d "/var/lib/lightdm/.config" ]; then
      cp -f roles/display/files/monitors.xml /var/lib/lightdm/.config/monitors.xml
      chown lightdm:lightdm /var/lib/lightdm/.config/monitors.xml
    fi
  when: xorg_configs.changed
  tags:
  - display