---
- name: create xorg configs
  copy:
    src: "{{ item }}"
    dest: /etc/X11/Xsession.d/
    owner: root
    group: root
    mode: 0777
  with_items:
  - files/01touchscreen
  - files/02scale
  tags:
  - display
  
- name: copy monitors.xml config in to place
  shell: |
    # install for users
    for USER in $(ls /home); do
      mkdir -p /home/${USER}/.config/
      if ! (grep -q right "/home/${USER}/.config/monitors.xml" || false); then
        if ! (grep -q "DSI-1" "/home/${USER}/.config/monitors.xml" || false); then
          cp -vf roles/display/files/monitors.xml /home/${USER}/.config/monitors.xml
          chown -R ${USER}:${USER} /home/${USER}/.config/
        fi
      fi
    done
    
    # install for gdm
    if [ -d "/var/lib/gdm3/.config" ]; then
      if ! (grep -q right "/var/lib/gdm3/.config/monitors.xml" || false); then
        if ! (grep -q "DSI-1" "/var/lib/gdm3/.config/monitors.xml" || false); then
          cp -vf roles/display/files/monitors.xml /var/lib/gdm3/.config/monitors.xml
          chown gdm:gdm /var/lib/gdm3/.config/monitors.xml
        fi
      fi
    fi
    
    # install for lightdm
    if [ -d "/var/lib/lightdm/.config" ]; then
      if ! (`grep -q right "/var/lib/lightdm/.config/monitors.xml"` || false); then
        if ! (grep -q "DSI-1" "/var/lib/lightdm/.config/monitors.xml" || false); then
          cp -vf roles/display/files/monitors.xml /var/lib/lightdm/.config/monitors.xml
          chown lightdm:lightdm /var/lib/lightdm/.config/monitors.xml
        fi
      fi
    fi
  register: monitors_copy
  changed_when: monitors_copy.stdout.find('->') != -1
  tags:
  - display