---
- name: install kernel dependencies [arch]
  pacman: name="{{ item }}"
  with_items:
  - base-devel
  - btrfs-progs
  - bzip2
  - bc
  - docbook-xsl
  - git
  - inetutils
  - kmod
  - tar
  - xmlto
  when: ansible_distribution == 'Archlinux'
  tags:
  - kernel

- name: install kernel dependencies [debian]
  apt: name="{{ item }}"
  with_items:
  - build-essential
  - bzip2
  - git
  - libncurses5-dev
  - libssl-dev
  - tar
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  tags:
  - kernel

- name: install bootstrap kernel
  shell: |
    mkdir -p /tmp/linux-bootstrap
    tar -xvjpf roles/kernel/files/linux-bootstrap.tar.bz2 -C /tmp/linux-bootstrap/
    cp -ar /tmp/linux-bootstrap/boot/* /boot/
    if [ -f /usr/bin/apt-get ]; then
      cp -arf /tmp/linux-bootstrap/lib/* /lib/
      update-initramfs -u -k 4.12.0-custom
    elif [ -f /usr/bin/pacman ]; then
      cp -arf /tmp/linux-bootstrap/lib/* /usr/lib/
      mkinitcpio -c /etc/mkinitcpio.conf -g /boot/linux-custom.img -k 4.12.0-custom || true
      pacman -R --noconfirm linux
    fi
    rm -rf /tmp/linux-bootstrap    
  when: bootstrap | default("false") | match("true")
  tags:
  - kernel

- name: fetch latest kernel sources (this will take a while)
  git:
    repo: https://github.com/jwrdegoede/linux-sunxi.git
    dest: /usr/src/linux-sunxi
    version: 52d94b5c09fa5464da113ff8c93c58e31e4a64d4
    force: yes
  when: bootstrap | default("false") | match("false")
  register: kernel_sources
  tags:
  - kernel

- name: build kernel (this will take a while)
  make:
    chdir: /usr/src/linux-sunxi
    target: -j9
    params:
      LOCALVERSION: -custom
  when: kernel_sources.changed
  tags:
  - kernel

- name: install kernel modules
  make:
    chdir: /usr/src/linux-sunxi
    target: modules_install
  when: kernel_sources.changed
  tags:
  - kernel
  
- name: install kernel
  make:
    chdir: /usr/src/linux-sunxi
    target: install
  when: kernel_sources.changed
  tags:
  - kernel

- name: add modules to initramfs [arch]
  lineinfile:
    path: /etc/mkinitcpio.conf
    regexp: '^MODULES='
    line: MODULES="btusb pwm-lpss pwm-lpss-platform"
    create: yes
  notify:
  - mkinitcpio
  when: ansible_distribution == 'Archlinux'
  tags:
  - kernel

- name: add modules to initramfs [debian]
  lineinfile:
    path: /etc/initramfs-tools/modules
    line: "{{ item }}"
    create: yes
  with_items:
  - btusb
  - pwm-lpss
  - pwm-lpss-platform
  notify:
  - update-initramfs
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  tags:
  - kernel