---
- name: install gpd patched kernel
  shell: dpkg -i roles/kernel/files/*.deb

- name: add pwm modules to initramfs
  lineinfile:
    path: /etc/initramfs-tools/modules
    line: "{{ item }}"
  register: initramfs_modules
  with_items:
  - pwm-lpss
  - pwm-lpss-platform
  
- name: update initramfs
  shell: update-initramfs -u -k all
  when: initramfs_modules.changed