---
- name: install kernel dependencies [arch]
  pacman: name="{{ item }}"
  with_items:
  - base-devel
  - btrfs-progs
  - bc
  - git
  - inetutils
  - kmod
  - libelf
  when: ansible_distribution == 'Archlinux'
  tags:
  - kernel

- name: install kernel dependencies [debian]
  apt: name="{{ item }}"
  with_items:
  - build-essential
  - git
  - libelf-dev
  - libncurses5-dev
  - libssl-dev
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  tags:
  - kernel

- name: fetch latest prebuilt kernel (this will take a while)
  git:
    repo: https://github.com/cawilliamson/linux-gpdpocket.git
    dest: /usr/src/linux-gpdpocket
    force: yes
  register: kernel_sources
  tags:
  - kernel

- name: install kernel modules
  make:
    chdir: /usr/src/linux-gpdpocket
    target: modules_install
  when: kernel_sources.changed
  tags:
  - kernel

- name: install new kernel
  copy:
    src: /usr/src/linux-gpdpocket/arch/x86/boot/bzImage
    dest: /boot/vmlinuz-4.12.0-gpdpocket
    owner: root
    group: root
    mode: 0644
  notify:
  - update initrd
  - update grub
  when: kernel_sources.changed
  tags:
  - kernel

- name: add modules to initramfs [arch]
  lineinfile:
    path: /etc/mkinitcpio.conf
    regexp: '^MODULES='
    line: MODULES="btusb pwm-lpss pwm-lpss-platform"
    create: yes
  notify:
    - update initrd
    - update grub
  when: ansible_distribution == 'Archlinux'
  tags:
  - kernel

- name: change hook loading order [arch]
  lineinfile:
    path: /etc/mkinitcpio.conf
    regexp: '^HOOKS='
    line: HOOKS="base udev block autodetect modconf filesystems fsck"
    create: yes
  notify:
    - update initrd
    - update grub
  when: ansible_distribution == 'Archlinux'
  tags:
  - kernel

- name: add modules to initramfs [debian]
  lineinfile:
    path: /etc/initramfs-tools/modules
    line: "{{ item }}"
    create: yes
  with_items:
  - btusb
  - pwm-lpss
  - pwm-lpss-platform
  notify:
    - update initrd
    - update grub
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  tags:
  - kernel