---
- name: install gpd patched kernel
  apt:
    deb: "{{ item }}"
    install_recommends: no
    update_cache: no
  with_fileglob:
  - "files/*.deb"

- name: add pwm modules to initramfs
  lineinfile:
    path: /etc/initramfs-tools/modules
    line: "{{ item }}"
    create: yes
  register: initramfs_modules
  with_items:
  - pwm-lpss
  - pwm-lpss-platform
  
- name: update initramfs
  shell: update-initramfs -u -k all
  when: initramfs_modules.changed