---
- name: copy files to device
  copy:
    src: "{{ item }}"
    dest: /tmp/
    owner: root
    group: root
    mode: 0644
  with_fileglob:
  - "files/*.deb"

- name: install gpd patched kernel
  apt: deb=/tmp/*.deb
  
- name: remove deb files
  file:
    path: /tmp/*.deb
    state: absent