---
- name: install gpd patched kernel
  apt:
    deb: "{{ item }}"
    install_recommends: no
    update_cache: no
  with_fileglob:
  - "files/*.deb"

- name: add pwm modules to initramfs
  lineinfile:
    path: /etc/initramfs-tools/modules
    line: "{{ item }}"
    create: yes
  notify:
  - rebuild initramfs
  with_items:
  - pwm-lpss
  - pwm-lpss-platform