---
- name: create ucm directory
  file:
    path: /usr/share/alsa/ucm/chtrt5645
    state: directory

- name: copy audio config files to device
  copy:
    src: "{{ item }}"
    dest: /usr/share/alsa/ucm/chtrt5645/
    owner: root
    group: root
    mode: 0644
  notify:
  - set default audio
  with_fileglob:
  - "files/*.conf"

- name: fix pulseaudio config [1]
  lineinfile:
    path: /etc/pulse/daemon.conf
    line: 'realtime-scheduling = no'

- name: fix pulseaudio config [2]
  lineinfile:
    path: /etc/pulse/daemon.conf
    regexp: '^realtime-scheduling = yes'
    state: absent
    
- name: fix pulseaudio config [3]
  lineinfile:
    path: /etc/pulse/default.pa
    regexp: '^#set-default-sink'
    line: 'set-default-sink 1'
    
- name: fix pulseaudio config [4]
  lineinfile:
    path: /etc/pulse/default.pa
    regexp: '^#set-default-source'
    line: 'set-default-source 1'