---
- name: enable gpdrotate
  systemd:
    name: gpdrotate
    daemon_reload: yes
    enabled: yes
  listen: enable gpdrotate

- name: update dconf
  shell: dconf update
  ignore_errors: yes
  listen: update dconf