---
- name: enable gpdrotate
  systemd:
    name: gpdrotate
    daemon_reload: yes
    enabled: yes
  listen: enable gpdrotate

- name: enable gpdfand
  systemd:
    name: gpdfand
    daemon_reload: yes
    enabled: yes
  listen: enable gpdfand

- name: enable thermal services
  service:
    name: "{{ item }}"
    enabled: yes
  with_items:
  - thermald
  - tlp
  listen: enable thermal services

- name: set default audio
  shell: pacmd set-default-sink "alsa_output.platform-cht-bsw-rt5645.HiFi__hw_chtrt5645__sink" || true
  listen: set default audio