---
- name: enable gpdfand
  systemd:
    name: gpdfand
    daemon_reload: yes
    enabled: yes
    state: started
  listen: enable gpdfand
  
- name: restart tlp
  systemd:
    name: tlp
    state: restarted
  listen: restart tlp