---
- name: remove old audio files from wrong location
  file:
    path: "{{ item }}"
    state: absent
  with_items:
  - /usr/share/alsa/ucm/HiFi.conf
  - /usr/share/alsa/ucm/chtrt5645.conf
  tags:
  - cleanup
  - common

- name: remove old xorg configs
  file:
    path: "{{ item }}"
    state: absent
  with_items:
  - /etc/X11/Xsession.d/98gpdrotate
  - /etc/X11/Xsession.d/98touchscreen
  - /etc/X11/Xsession.d/99touchscreen
  tags:
  - cleanup
  - common
  
- name: remove old rc.local hacks
  lineinfile:
    path: /etc/rc.local
    regexp: "{{ item }}"
    state: absent
  with_items:
  - '^modprobe btusb'
  - '^echo "0000 0000"'
  tags:
  - cleanup
  - common
  
- name: remove old gpdfand script
  file:
    path: /usr/local/bin/gpdfand
    state: absent
  tags:
  - cleanup
  - common
  
- name: remove old copies of git repository
  file:
    path: /root/ansible-gpdpocket
    state: absent
  tags:
  - cleanup
  - common

- name: remove udev config for bluetooth (no longer needed)
  file:
    path: /etc/udev/rules.d/99-local-bluetooth.rules
    state: absent
  tags:
  - cleanup
  - common
  
- name: remove old monitors.xml configs
  file:
    path: "{{ item }}"
    state: absent
  with_items:
  - "/var/lib/lightdm/.config/monitors.xml"
  - "/var/lib/gdm3/.config/monitors.xml"
  tags:
  - cleanup
  - common
  
- name: remove old kernel files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
  - /boot/vmlinuz
  - /boot/config-4.12.0-custom
  - /boot/initrd.img-4.12.0-custom
  - /boot/system.map-4.12.0-custom
  - /boot/vmlinuz-4.12.0-custom
  - /lib/modules/4.12.0-custom
  - /usr/src/linux-sunxi
  tags:
  - cleanup
  - common
  
- name: delete log path for gpdfand
  file:
    path: /var/log/gpdfand
    state: absent
  tags:
  - cleanup
  - common