---
- name: copy gpdfand daemon
  copy:
    src: files/fan/gpdfand.py
    dest: /usr/local/sbin/gpdfand
    owner: root
    group: root
    mode: 0777
  tags:
  - fan

- name: add suspend script for gpdfand
  copy:
    src: files/fan/gpdfand
    dest: /lib/systemd/system-sleep/gpdfand
    owner: root
    group: root
    mode: 0777
  tags:
  - fan

- name: copy config file for gpdfand
  copy:
    src: files/fan/gpdfand.conf
    dest: /etc/gpdfand.conf
    owner: root
    group: root
    mode: 0644
    force: no
  tags:
  - fan

- name: copy systemd service for gpdfand
  copy:
    src: files/fan/gpdfand.service
    dest: /etc/systemd/system/gpdfand.service
    owner: root
    group: root
    mode: 0644
  notify:
  - enable gpdfand
  tags:
  - fan