---
- name: create ucm directory
  file:
    path: /usr/share/alsa/ucm
    state: directory

- name: copy audio config files to device
  copy:
    src: "{{ item }}"
    dest: /usr/share/alsa/ucm/
    owner: root
    group: root
    mode: 0644
  with_fileglob:
  - "files/*.conf"