---
- name: add boot options to grub
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT='
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="i915.fastboot=1 i915.semaphores=1"'
  notify:
  - update grub
  tags:
  - grub

- name: reduce grub timeout
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_TIMEOUT='
    line: 'GRUB_TIMEOUT=3'
  notify:
  - update grub
  tags:
  - grub