---
- name: add grub config fix
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT="'
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="i915.fastboot=1 i915.semaphores=1"'
  tags:
  - grub

- name: update grub
  shell: grub-mkconfig -o /boot/grub/grub.cfg