---
- name: add grub config fix
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT="'
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="i915.fastboot=1 intel_pstate=disable"'

- name: generate grub config
  shell: update-grub