---
- name: install gpdfand dependencies
  shell: dpkg -i roles/fan/files/deb/*.deb

- name: copy gpdfand daemon
  copy:
    src: files/scripts/gpdfand.pl
    dest: /usr/local/bin/gpdfand
    owner: root
    group: root
    mode: 0755

- name: copy systemd service for gpdfand
  copy:
    src: files/scripts/gpdfand.service
    dest: /etc/systemd/system/gpdfand.service
    owner: root
    group: root
    mode: 0644
  notify:
  - reload systemd
  - enable service
    
- name: add suspend script for gpdfand
  copy:
    src: files/scripts/gpdfand
    dest: /lib/systemd/system-sleep/gpdfand
    owner: root
    group: root
    mode: 0755
    