---
- name: install gpdfand dependencies
  apt: name="{{ item }}"
  with_items:
  - libproc-daemon-perl
  - libproc-pid-file-perl
  - liblog-dispatch-perl

- name: copy gpdfand daemon
  copy:
    src: files/gpdfand.pl
    dest: /usr/local/sbin/gpdfand
    owner: root
    group: root
    mode: 0777

- name: copy systemd service for gpdfand
  copy:
    src: files/gpdfand.service
    dest: /etc/systemd/system/gpdfand.service
    owner: root
    group: root
    mode: 0644
  notify:
  - reload systemd
  - enable service
    
- name: add suspend script for gpdfand
  copy:
    src: files/gpdfand
    dest: /lib/systemd/system-sleep/gpdfand
    owner: root
    group: root
    mode: 0777
    
- name: create log path for gpdfand
  file:
    path: /var/log/gpdfand
    state: directory
    owner: root
    group: root
    mode: 0666